[package]
name = "programming_bitcoin"
version = "0.1.0"
authors = ["Frost Red <frostredlee@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
num-bigint = "0.2"
num-traits = "0.2"
